# fastlane/Fastfile

# Define defult platform as iOS
default_platform(:ios)

platform :ios do
	desc "Kod stilini kontrol eder"
  	lane :lint do
    		swiftlint(
      			executable: "swiftlint",
      			strict: false,
      			output_file: "fastlane/swiftlint-report.html",
      			reporter: "html"
    		)
  	end

    desc "Run all tests ve report the results"
    lane :tests do
	lint
        scan(
            scheme: "OptimizedGridLoader",
            destination: "platform=iOS Simulator,name=iPhone 17 Pro Max,OS=latest",
            clean: true,
            build_for_testing: true,
            output_directory: "fastlane/test_output"
        
        )
    end
end